# Spring
# ----------------------------------------------------------------------------------------------------------------------
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/uaa
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uaa?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: postgres
    password: 1234
