# Spring
# ----------------------------------------------------------------------------------------------------------------------
spring:

  # Database
  data:
    mongodb:
      uri: mongodb://localhost:27017/product

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8901/auth/realms/ashina

  # Cloud
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
          auto-create-topics: false
          configuration:
            auto.offset.reset: latest
      bindings:
        product-reserved-request-in:
          destination: "product.reserved.request"
          group: "${spring.application.name}"
          contentType: application/json
        product-reserved-rollback-in:
          destination: "product.reserved.rollback"
          group: "${spring.application.name}"
          contentType: application/json
        product-reserved-response-out:
          destination: "product.reserved.response"
          contentType: application/json

# Eureka client
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
