# Spring
# ----------------------------------------------------------------------------------------------------------------------
spring:

  # Database
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8901/auth/realms/ashina

# Eureka client
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
