# ======================================================================================================================
# Spring
# ======================================================================================================================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
      bindings:
        order-created-source:
          destination: "order.created"
        order-canceled-source:
          destination: "order.canceled"

# ======================================================================================================================
# Eureka client
# ======================================================================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
