# Spring
# ----------------------------------------------------------------------------------------------------------------------
spring:

  # Database
  data:
    mongodb:
      uri: mongodb://localhost:27017/orders

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8901/auth/realms/ashina

  # Cloud
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
          auto-create-topics: false
          configuration:
            auto.offset.reset: latest
      bindings:
        reserve-product-reply-in:
          destination: "reserve.product.reply"
          group: "${spring.application.name}"
          contentType: application/json
        create-payment-reply-in:
          destination: "create.payment.reply"
          group: "${spring.application.name}"
          contentType: application/json
        reserve-product-out:
          destination: "reserve.product"
          contentType: application/json
        reserve-product-rollback-out:
          destination: "reserve.product.rollback"
          contentType: application/json
        create-payment-out:
          destination: "create.payment"
          contentType: application/json
        complete-order-out:
          destination: "complete.order"
          contentType: application/json

# Eureka client
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
