# Spring
# ----------------------------------------------------------------------------------------------------------------------
spring:

  # Security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8901/auth/realms/ashina/protocol/openid-connect/token
            authorization-uri: http://localhost:8901/auth/realms/ashina/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8901/auth/realms/ashina/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-dev:
            provider: keycloak
            client-id: gateway
            client-secret: c7c7ee6a-c989-4bf0-9308-d5a56cde2f8d
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
