# Server
# ---------------------------------------------------------------------------------------------------------------------
server:
  port: 8080

# Logging
# ---------------------------------------------------------------------------------------------------------------------
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: TRACE

# Spring
# ----------------------------------------------------------------------------------------------------------------------
spring:

  # Cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product-service/**
          filters:
            - RewritePath=/api/product-service/(?<segment>.*), /api/$\{segment}
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer-service/**
          filters:
            - RewritePath=/api/customer-service/(?<segment>.*), /api/$\{segment}
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory-service/**
          filters:
            - RewritePath=/api/inventory-service/(?<segment>.*), /api/$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order-service/**
          filters:
            - RewritePath=/api/order-service/(?<segment>.*), /api/$\{segment}

  # Security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8901/auth/realms/ashina/protocol/openid-connect/token
            authorization-uri: http://localhost:8901/auth/realms/ashina/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8901/auth/realms/ashina/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-dev:
            provider: keycloak
            client-id: gateway
            client-secret: c7c7ee6a-c989-4bf0-9308-d5a56cde2f8d
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
