# Security
# ----------------------------------------------------------------------------------------------------------------------
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8901/api/v1/rsa/public-key

# Eureka client
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
