# Spring
# ----------------------------------------------------------------------------------------------------------------------
spring:

  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8901/auth/realms/ashina

# Eureka client
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# UAA
# ----------------------------------------------------------------------------------------------------------------------
uaa:
  keycloak:
    server-url: http://localhost:8901/auth
    realm: ashina
    client-id: admin-cli
    username: admin-cli
    password: 12345678
